### ISSUE TITLE
install not working on linux

### ISSUE THREAD

**Issue by assembledStarDust** [jsingh811/pyAudioProcessing#17]
Install not working on linux - unfulfilled dependency ```python-magic-bin==0.4.14```

detail: Centos 8
Clone repo ```git clone https://github.com/jsingh811/pyAudioProcessing.git```

install with ```pip3 install -e . ```

Failed dependency
```
  Downloading https://files.pythonhosted.org/packages/79/db/eaf620b73a1eec3c8c6f8f5b0b236a50f9da88ad57802154b7ba7664d0b8/pydub-0.23.1-py2.py3-none-any.whl
Collecting python-magic-bin==0.4.14 (from pyAudioProcessing==1.1.6)
  Could not find a version that satisfies the requirement python-magic-bin==0.4.14 (from pyAudioProcessing==1.1.6) (from versions: )
No matching distribution found for python-magic-bin==0.4.14 (from pyAudioProcessing==1.1.6)
```

Reviewing [python-magic-bin](https://pypi.org/project/python-magic-bin/#files), I don't see a linux version. 

Can you advise?

**Comment by jsingh811** [comment]
@assembledStarDust Thanks for creating the issue. The requirements have been fixed and updated in the master branch.
Please pull the latest master branch of the project and try again. Thank you!
