### ISSUE TITLE
Example dont work

### ISSUE THREAD

**Issue by pa-blan** [jsingh811/pyAudioProcessing#2]
Hi I have tried the examples but always is not classified correctly. 
What am I doing wrong?
###############################################################
`
 There are 2 classes in the specified data folder

 Classifying using features mfcc with classifier randomforest that is saved as svm_clf

        

 data_samples/testing\music
0 out of 3 instances were classified correctly

 data_samples/testing\speech
0 out of 3 instances were classified correctly

Results saved in classifier_results.json

Process finished with exit code 0
#######################################################`

But when I look into the json I see correct assignments

`{
 "data_samples/testing\\music": {
  "beatles.wav": {
   "probabilities": [
    1.0,
    0.0
   ],
   "classes": [
    "music",
    "speech"
   ]
  },
  "nearhou.wav": {
   "probabilities": [
    0.856,
    0.144
   ],
   "classes": [
    "music",
    "speech"
   ]
  },
  "opera.wav": {
   "probabilities": [
    0.432,
    0.568
   ],
   "classes": [
    "music",
    "speech"
   ]
  }
 },
 "data_samples/testing\\speech": {
  "acomic.wav": {
   "probabilities": [
    0.0,
    1.0
   ],
   "classes": [
    "music",
    "speech"
   ]
  },
  "sleep.wav": {
   "probabilities": [
    0.308,
    0.692
   ],
   "classes": [
    "music",
    "speech"
   ]
  },
  "smoking.wav": {
   "probabilities": [
    0.078,
    0.922
   ],
   "classes": [
    "music",
    "speech"
   ]
  }
 }
}`

**Comment by jsingh811** [comment]
These are the exact steps I followed 
```
python pyAudioProcessing/run_classification.py -f "data_samples/training" -clf "randomforest" -clfname "rf_clf" -t "train" -feats "mfcc"
```
```
python pyAudioProcessing/run_classification.py -f "data_samples/testing" -clf "randomforest" -clfname "rf_clf" -t "classify" -feats "mfcc"
```
the classification resulted in these logs
```
 There are 2 classes in the specified data folder


 Classifying using features mfcc with classifier randomforest that is saved as rf_clf

        

 data_samples/testing/music
2 out of 2 instances were classified correctly

 data_samples/testing/speech
2 out of 2 instances were classified correctly

Results saved in classifier_results.json
```
and it matches what I see in the classifier_results.json file.
This was tested on linux/mac environment.
